baseURL = 'https://robotamateur123.github.io/'
languageCode = 'en-us'
title = 'Robot Amateur'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "Welcome!", Content = "Learn Robotics & AI by Making 🚀" }
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
